# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fbf785ccf288b773ca376694cea3a49452c2b83bb8ab9acb74b67db62cfea09e27b6ce54975638d70a853d13d4ef1632d5d963d45bb03d3fa47034c5a553fd54

test:
  secret_key_base: 3b4e72913f8c99f7010360ddb74dfcf4fb559016ed0f2b75704f67c51f0cb1e0d40d02425bdbe43312d79191f0fde6bb6c65c292eb0cefaeed3b5156af4fdc69

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
